---
# TECDE hyperparameters (taken from original work)


# defaults
learning_rate: 0.0001

hidden_size: 8

hidden_layers:
  - [128, 128]

mc_samples: 10

dropout_probability: 0.1

dropout_type: 'dropout_head'

prediction_window: [1,2,3,4,5]

intensity_weighting: False

method: 'euler'

interpolation_method: 'spline'

control_size: 7

treatment_size: 4

clip_grad: 0.0

batch_size: 64

max_epochs: 500

patience: 10

...